// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrlouoongmdtritwojaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndybG91b29uZ21kdHJpdHdvamF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDU2MTMsImV4cCI6MjA3MDkyMTYxM30._zo2qW9SFpYSV9jz-wedjOuB2Gp4BFxqsBKwaUQSnlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});